#!/bin/bash
printf "%o\n" $(((echo(($WATER | tr water 01234) + ($STIR | tr stir))))
#printf '%o\n' $(( 5#$( echo $WATER | tr water 01234) + 5#$( echo $STIR | tr stir. 01234 ) )) | tr 01234567 behlnort
