#!/usr/bin/env bash
#Configures a ubuntu server to install HAProxy
apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
myVars="\n\tbind :80\n\tmode http\n\tuse_backend mybackend\nbackend mybackend\n\tbalance roundrobin\n\tserver 47011-web-01 44.200.41.28:80 check\n\tserver 47011-web-02 52.73.26.113:80 check"
sed -i '/errorfile 504/a frontend myconf' /etc/haproxy/haproxy.cfg
sed -i "s/frontend myconf/&$myVars/g" /etc/haproxy/haproxy.cfg
service haproxy start
