#!/usr/bin/env bash
#Configures a ubuntu server to install HAProxy
apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
sed -i '/504.http/a \\nlisten chalo\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 47011-web-01 44.200.41.28:80 check\n\tserver 47011-web-02 52.73.26.113:80 check' /etc/haproxy/haproxy.cfg
service haproxy start
