#!/usr/bin/env bash
#Install and configure nginx on ubuntu:14.04 docker container to be exposed on port 80

sudo apt-get -y update
sudo apt-get -y install nginx curl ufw
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/ipv6only=on//g' /etc/nginx/sites-enabled/default
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
