#!/usr/bin/env bash
#Install and configure nginx on ubuntu:14.04 docker container to be exposed on port 80

sudo apt-get -y update && sudo apt-get -y install nginx
sudo apt-get -y install ufw
sudo ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
