#!/usr/bin/env bash
#Installs and configures ufw to allow traffic on ports 22, 443, 80

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw disable
sudo ufw reset
sudo ufw allow ssh
sudo ufw allow 443/https
sudo ufw allow 80/http
sudo ufw enable
